server:
  port: 8080
spring:
  application:
    name: \${env.appName}
  messages:
    basename: i18n
    encoding: UTF-8
  threads:
    virtual:
      enabled: true
  jpa:
    show-sql: false
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:./data/nastoys.db
management:
  endpoints:
    web:
      exposure:
        include: info,health
logging:
  config: classpath:logback-spring-dev.xml
  file:
    path: classpath:/
    name: data/log
  charset:
    file: UTF-8
springdoc:
  show-actuator: true
  swagger-ui:
    filter: true
env:
  appName: "${name}"
  isEnableSwagger: false
  libs: classpath:/libs
  jwt:
    expire: 30
    tokenHeader: Authorization
    tokenPrefix: 'Bearer'
    privateKey: classpath:private.pem
    publicKey: classpath:public.pem
  mqtt:
    username: nas
    password: lijiawei
    default-topic:
      - "test/topic"
    host: "ssl://localhost:1883"
