server:
  port: 8080
spring:
  application:
    name: ${env.appName}
  messages:
    basename: i18n
    encoding: UTF-8
  threads:
    virtual:
      enabled: true
  jpa:
    show-sql: true
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:db.sqlite

logging:
  config: classpath:logback-spring-dev.xml
  file:
    path: classpath:/
    name: log
  charset:
    file: UTF-8
springdoc:
  show-actuator: true
  swagger-ui:
    filter: true
env:
  appName: 'spring-boot-template'
  version: '0.0.1'
  isEnableSwagger: true
  libs: classpath:/libs
  jwt:
    expire: 30
    tokenHeader: Authorization
    tokenPrefix: 'Bearer'
    privateKey: classpath:private.pem
    publicKey: classpath:public.pem
  mqtt:
    username: nas
    password: lijiawei
    default-topic:
      - "test/topic"
    host: "ssl://localhost:1883"
